version: '3'
services:

    db:
        image: mysql:5.7
        container_name: lschat-mysql
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3316:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password-lsemi
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
